### ISSUE TITLE
Update icon (again)

### ISSUE THREAD

**Issue by AndhikaWB** [Sebazzz/fiddlerfox#4]
Hi,

This extension has been useful to me lately. Unfortunately, it has no icon at least on Firefox 72. Not a big deal though, just wanna let you know.
![image](https://user-images.githubusercontent.com/17119394/75469982-864de200-59c2-11ea-9fc0-17668da1d509.png)

**Comment by Sebazzz** [comment]
Good to hear! I will look into it.

**Comment by AndhikaWB** [comment]
Uh thanks, unfortunately this only fix the main icon. The toolbar icon is still empty (my bad, didn't mention it earlier).
![image](https://user-images.githubusercontent.com/17119394/75506744-8aedb700-5a11-11ea-94ee-49858d489fc2.png)

**Comment by Sebazzz** [comment]
You're right. Apologies. I suspect this broke in a Firefox update, it used to work.

**Comment by Sebazzz** [comment]
Published 0.4 - it may take a short time to be published on AMO.
